### ISSUE TITLE
Deprecated Repo?

### ISSUE THREAD

**Issue by jasedit** [ECE4574-5574/App#5]
Is this repo in use anymore, or has it been superseded by the MobileApp repository? If it's deprecated, it would be nice if we could mark it as deprecated or delete it as makes sense.

**Comment by ghost** [comment]
I'm going to keep a copy of the repo but I would prefer you don't delete repositories. If you feel the prefix "depricated-" to the name if no one is contributing to it then do so.

**Comment by jasedit** [comment]
I marked the previous simulator attempt as “prototype” to mark it as no longer under active development, so that matches how I would prefer it. I’m just making sure that my understanding from looking at repos and the app team’s current mental state match up. If a Team 1 member could confirm, I’m happy to make the name switch (or allow them to make the appropriate changes.)
